spring:
  application:
    name: camel-racing-system

  profiles:
    active: dev

  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        query:
          fail_on_pagination_over_collection_fetch: true

server:
  port: ${SERVER_PORT:8080}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    doc-expansion: none
    display-request-duration: true
    oauth:
      client-id: camel-racing-swagger
      use-pkce-with-authorization-code-grant: true

keycloak:
  public-url: ${KEYCLOAK_PUBLIC_URL:http://localhost:8180}